CS4437-Big-Data-Management-Team-1/LMS-Development-Repo

user-service/pom.xml, user-service/src/main/java/com/lms/userservice/controller/UserController.java, user-service/src/main/resources/log4j.xml
As per design document said we would use log4j for logging in project. Added in logging in User-service eg output as running commands
=> Log4j Logging at different levels for registration and login

user-service/src/main/java/com/lms/userservice/controller/UserController.java, user-service/src/test/java/com/lms/userservice/controller/UserControllerTest.java
Updated UserController unit tests currently at this coverage 
I am only testing the internal logic. Tried to mock firebase and stuff to get it working but cannot. Think it would make more sense to include this testing in the Integration testing when we get to this (will probably be one of the last things we do) as we are interacting with external service.
=> Fixup of unit tests for User Controller

information-service/src/main/java/com/lms/informationservice/InformationServiceApplication.java, information-service/src/main/java/com/lms/informationservice/database/InformationDatabaseController.java, information-service/src/main/resources/application.properties, information-service/src/main/resources/database.properties, notification-service/pom.xml, notification-service/src/main/java/com/lms/notificationservice/NotificationServiceApplication.java, notification-service/src/main/java/com/lms/notificationservice/database/NotificationDatabaseController.java, notification-service/src/main/java/com/lms/notificationservice/service/NotificationService.java, notification-service/src/main/resources/application.properties, notification-service/src/main/resources/database.properties, user-service/src/main/java/com/lms/userservice/UserServiceApplication.java, user-service/src/main/java/com/lms/userservice/database/UserDatabaseConnector.java, user-service/src/main/resources/application.properties, user-service/src/main/resources/database.properties
Added functionality to add email record to database. Still needs to be connected to some method or endpoint, right now its only through main
=> Mharrison add email record

information-service/src/main/java/com/lms/informationservice/InformationServiceApplication.java, notification-service/src/main/java/com/lms/notificationservice/NotificationServiceApplication.java, payment-service/pom.xml, payment-service/src/main/java/com/lms/paymentservice/PaymentServiceApplication.java, payment-service/src/main/java/com/lms/paymentservice/controller/PaymentController.java, payment-service/src/main/java/com/lms/paymentservice/database/PaymentDatabaseController.java, payment-service/src/main/java/com/lms/paymentservice/model/PaymentResponse.java, payment-service/src/main/java/com/lms/paymentservice/service/PaymentService.java, payment-service/src/main/resources/application.properties, user-service/src/main/java/com/lms/userservice/UserServiceApplication.java
Payments are now added to payments table when processed.
Right now default value for user_id of each payment is hardcoded as 4 since services aren't linked yet
=> Mharrison payment added to db

game-service/pom.xml, game-service/src/main/java/com/lms/gameservice/GameServiceApplication.java, game-service/src/main/java/com/lms/gameservice/controller/GameController.java, game-service/src/main/java/com/lms/gameservice/model/Game.java, game-service/src/main/java/com/lms/gameservice/model/Player.java, game-service/src/main/java/com/lms/gameservice/model/PlayerPick.java, game-service/src/main/java/com/lms/gameservice/model/Round.java, game-service/src/main/java/com/lms/gameservice/repository/GameRepository.java, game-service/src/main/java/com/lms/gameservice/repository/PlayerPickRepository.java, game-service/src/main/java/com/lms/gameservice/repository/PlayerRepository.java, game-service/src/main/java/com/lms/gameservice/service/GameService.java, game-service/src/main/java/com/lms/gameservice/service/InformationServiceClient.java, game-service/src/main/java/com/lms/gameservice/service/PaymentServiceClient.java, game-service/src/main/java/com/lms/gameservice/service/RoundService.java, game-service/src/main/resources/applications.properties.properties, game-service/src/test/java/com/lms/gameservice/GameServiceTests.java, pom.xml
Base skeleton for game service in, if can review quick very very base now. Will be changes tried do as quick as could to get outline of core features
=> Game service start

payment-service/src/main/java/com/lms/paymentservice/PaymentServiceApplication.java, payment-service/src/main/java/com/lms/paymentservice/controller/PaymentController.java, payment-service/src/main/java/com/lms/paymentservice/handler/PaymentExceptionHandler.java, payment-service/src/main/java/com/lms/paymentservice/model/PaymentRequest.java, payment-service/src/main/java/com/lms/paymentservice/model/PaymentResponse.java, payment-service/src/main/java/com/lms/paymentservice/service/PaymentService.java
Reverts CS4437-Big-Data-Management-Team-1/LMS-Development-Repo#25
Need to fix merge conflicts
=> Revert "Added javadocs to payment service"

game-service/src/main/java/com/lms/gameservice/controller/GameController.java, game-service/src/main/java/com/lms/gameservice/service/AuthService.java, payment-service/pom.xml, payment-service/src/main/java/com/lms/paymentservice/config/Config.java, payment-service/src/main/java/com/lms/paymentservice/controller/PaymentController.java, payment-service/src/main/java/com/lms/paymentservice/database/PaymentDatabaseController.java, payment-service/src/main/java/com/lms/paymentservice/model/PaymentRequest.java, payment-service/src/main/java/com/lms/paymentservice/model/PaymentResponse.java, payment-service/src/main/java/com/lms/paymentservice/service/AuthService.java, payment-service/src/main/java/com/lms/paymentservice/service/PaymentService.java, payment-service/src/main/resources/application.properties, user-service/src/main/java/com/lms/userservice/controller/UserController.java, user-service/src/main/java/com/lms/userservice/database/UserDatabaseConnector.java, user-service/src/main/java/com/lms/userservice/model/User.java, user-service/src/main/resources/application.properties, user-service/src/test/java/com/lms/userservice/controller/UserControllerTest.java, user-service/src/test/java/com/lms/userservice/model/UserTest.java
This pr connects the payment service to the user service, checking the jwt login token and passing it to the validate-jwt endpoint in users to return the user's id. Then, the payment is stored alongside the user id who made it.
Login validation
Once logged in
=> Mharrison connect user to payments

game-service/pom.xml, game-service/src/test/java/com/lms/gameservice/service/InformationServiceClientTest.java
Fixing unit test to read the test .env file
=> Game service communication: unit test fix

.gitignore, notification-service/src/main/java/com/lms/notificationservice/NotificationServiceApplication.java, notification-service/src/main/java/com/lms/notificationservice/controller/NotificationController.java, notification-service/src/main/java/com/lms/notificationservice/model/GameCreatedNotification.java, notification-service/src/main/java/com/lms/notificationservice/model/GameCreationNotification.java, notification-service/src/main/java/com/lms/notificationservice/model/GameJoinNotification.java, notification-service/src/main/java/com/lms/notificationservice/model/GameJoinedNotification.java, notification-service/src/main/java/com/lms/notificationservice/repository/NotificationRepository.java, notification-service/src/main/java/com/lms/notificationservice/service/NotificationService.java, notification-service/src/main/resources/application.properties, notification-service/src/test/java/com/lms/notificationservice/NotificationServiceApplicationTests.java, user-service/src/main/java/com/lms/userservice/controller/UserController.java
Integrated notification service with user service to send confirmation email.
Added javadoc comments.
Added unit tests for notifications.
=> Notification Service User Integration, Tests, Doc

game-service/pom.xml, game-service/src/main/java/com/lms/gameservice/matches/MatchesDTO.java, game-service/src/main/java/com/lms/gameservice/service/GameService.java, game-service/src/main/java/com/lms/gameservice/service/GameUpdateScheduler.java, game-service/src/main/java/com/lms/gameservice/service/InformationServiceClient.java, game-service/src/main/java/com/lms/gameservice/team/TeamDTO.java, game-service/src/test/java/com/lms/gameservice/service/InformationServiceClientTest.java, information-service/pom.xml
Game-service was too dependent on information-service. Fixed issue using DTO's
=> Fixing communication problem with services

game-service/src/test/java/com/lms/gameservice/PaymentServiceClientTest.java
=> PaymentServiceClient tests written and passing

notification-service/src/main/java/com/lms/notificationservice/controller/NotificationController.java, notification-service/src/main/java/com/lms/notificationservice/model/AccountCreationNotification.java, user-service/src/main/java/com/lms/userservice/config/RestTemplateConfig.java, user-service/src/main/java/com/lms/userservice/controller/UserController.java
Sends JWT Token to user email on account creation for future reference. Also moved resttemplate into config for user service for separation of concerns.
=> Send JWT Token to user email on account creation

game-service/src/main/java/com/lms/gameservice/controller/GameController.java, game-service/src/main/java/com/lms/gameservice/service/PlayerService.java
Added an endpoint to allow users to change their weekly team (in GameController). and fixed the implementation in PlayerService to properly update the tables
Table before request:
Table After request:
you can see Arsenal moves from the available array to unavailable array (on the right), and is selected as the players team for the week (left)
after the request Arsenal is removed from the unavailable arraya and put back into available, chelsea is now where Arsenal was
=> Change Team Endpoint Working Properly

game-service/pom.xml, game-service/src/main/java/com/lms/gameservice/controller/GameController.java, game-service/src/test/java/com/lms/gameservice/GameServiceTests.java, notification-service/src/main/java/com/lms/notificationservice/controller/NotificationController.java, notification-service/src/main/java/com/lms/notificationservice/model/AccountCreationNotification.java, notification-service/src/main/java/com/lms/notificationservice/model/GameCreationNotification.java, notification-service/src/main/java/com/lms/notificationservice/model/GameJoinNotification.java, notification-service/src/test/java/com/lms/notificationservice/NotificationServiceApplicationTests.java, user-service/src/main/java/com/lms/userservice/controller/UserController.java, user-service/src/test/java/com/lms/userservice/controller/UserControllerTest.java
You now receive email notifications when you create and join games with relevant information.
=> Notification Service Integration with Game Service

game-service/src/main/java/com/lms/gameservice/service/GameService.java, game-service/src/main/java/com/lms/gameservice/service/GameUpdateScheduler.java, game-service/src/test/java/com/lms/gameservice/GameUpdateSchedulerTests.java, notification-service/src/main/java/com/lms/notificationservice/controller/NotificationController.java, notification-service/src/main/java/com/lms/notificationservice/model/GameUpdateNotification.java
Integrated notification service with game service to provide email notifications providing updates to players assigned to games about their tournament.
=> Game Update Notifications

.gitignore, docker-compose.yml, game-service/Dockerfile, information-service/Dockerfile, notification-service/Dockerfile
Docker services now running on correct ports.
Updated gitignore for adjusted env names
To use docker:
Open Docker Desktop
Change directory into root dir i.e. LMS-Development-Repo folder
run mvn clean install (this will clean install all 5 services)
docker compose build
docker compose up
=> Docker Port Fix

docker-compose.yml, game-service/src/main/java/com/lms/gameservice/controller/GameController.java, game-service/src/test/java/com/lms/gameservice/GameServiceTests.java, notification-service/pom.xml, notification-service/src/main/java/com/lms/notificationservice/config/AppConfig.java, notification-service/src/main/java/com/lms/notificationservice/config/RabbitMQConfig.java, notification-service/src/main/java/com/lms/notificationservice/consumer/EmailConsumer.java, notification-service/src/main/java/com/lms/notificationservice/controller/NotificationController.java, notification-service/src/main/java/com/lms/notificationservice/model/GameCreationNotification.java, notification-service/src/main/java/com/lms/notificationservice/model/GameJoinNotification.java, notification-service/src/main/java/com/lms/notificationservice/service/NotificationService.java, notification-service/src/test/java/com/lms/notificationservice/NotificationServiceApplicationTests.java
Must launch RabbitMQ through docker for use.
NotificationService produces emails and EmailConsumer consumes and sends them.
Refactored most of the code to be more coherent and make more sense for the flow of things.
=> RabbitMQ Implementation for Notifications

docker-compose.yml, game-service/src/main/java/com/lms/gameservice/controller/GameController.java, game-service/src/main/java/com/lms/gameservice/service/AuthService.java, game-service/src/main/java/com/lms/gameservice/service/GameUpdateScheduler.java, game-service/src/main/java/com/lms/gameservice/service/InformationServiceClient.java, game-service/src/main/java/com/lms/gameservice/service/PaymentServiceClient.java, game-service/src/test/java/com/lms/gameservice/GameServiceTests.java, game-service/src/test/java/com/lms/gameservice/GameUpdateSchedulerTests.java, game-service/src/test/java/com/lms/gameservice/PaymentServiceClientTest.java, information-service/src/main/java/com/lms/informationservice/service/InformationService.java, payment-service/src/main/java/com/lms/paymentservice/service/AuthService.java, user-service/Dockerfile, user-service/src/main/java/com/lms/userservice/controller/UserController.java
Fixed issues with game and info service not locating env files correctly after our name change.
Docker is working now and api requests can be made between services as updated localhost requests to relevant container names for all existing requests between services. Application must now be run solely through docker due to this change of names.
Guide:
In the root directory run these commands:
mvn clean install
docker compose build
docker compose up
Make sure you have your env files named as follows:
game.env
information.env
user.env
payment.env
notification.env
=> Docker works (for real this time) and Fix for info + game service not working

user-service/src/main/java/com/lms/userservice/controller/UserController.java, user-service/src/test/java/com/lms/userservice/integration/UserServiceIntegrationTest.java
Now says this when register 
Tests all still pass changed one line to not return user object. Also had small fix needed be merged for itnegration for consistency
=> small fix for integration need merged and jsut better display message

information-service/src/test/resources/.env
Accidently deleted test .env file needed for integration tests
=> test .env file deleted by accident

.github/workflows/kuberneties/all-in-one.yml, game-service/src/main/java/com/lms/gameservice/service/GameService.java
added the file used for the kuberneties setup, this will change once we change to g-cloud. Also a small fix, the pot now updates when a player joins a game.
=> Kuberneties file & small change to fix pot updating
